### PR TITLE
Change ensure user token schema

### PR DESCRIPTION
**Pull request by Gabiras12**
Only renew user and application token if receives a token invalid error response and then redo the request. 

This does not change the lib in terms of how to use it. It's just a scalability improvement.

### CODE REVIEW

**Comment by Gabiras12** [comment]
Looks like this also contains update to V2 work...
I've published to npmjs a 2.0.1-beta.5 version to test on staging.

**Comment by Gabiras12** [comment]
@ArthurSeaton @biofractal

**Comment by ArthurSeaton** [comment]
A couple of comments.

First this puts stack v2 code into the develop branch. I'm not sure what the implication of that is (`develop` branch is where apps are deployed from but this is a stack pack so I don't know the rules here).

Second the version number isn't what I would have done. This stack pack is out of beta so I'd just have made this something like 2.1.0 because it introduces a new feature (assuming it's not a breaking change - is it?).

If you release a stack pack it's good to tag it (git tag) with the version. Usually you do this and in fact I think you posted a message to others suggesting it but I don't think you've done it this time! Maybe waiting for comments in which case... fair enough! I have been using a leading v for the tag. See the output of git tag for examples and follow the format.

On the code it looks to me like the change will affect consumers as the changed code differs in behaviour from the old code (in the /gpapi route). To me it looks like previously on error the code would always return a response whereas now it can throw without returning a response (from within the nested try/catch).

Also nested try/catches are quite hard to read. Maybe refactor into a function so each function only has a single try/catch? That would be my preference I think.

I can't comment on the higher level idea behind this as I'm not familiar with the gpapi token behaviour. @jonny is the man for that.

**Comment by ArthurSeaton** [comment]
Sorry... prematurely closed the PR due to hitting the wrong button - my bad!

One more thing. You test against `inner.Name` rather than `inner.name`. I assume that's right for this case as you'll have tested it but it looks odd. Just mentioning it...

**Pull request merged**
